# - name: Print Component Name
#  debug:
#   msg: Component = frontend

- name: Install Nginx
  yum:
    name: nginx
    state: present

- name: Start Nginx
  ansible.builtin.systemd:
    state: started
    name: nginx
    enabled: yes

- name: Remove old htdocs directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Extract package
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/frontend/archive/main.zip
    dest: /usr/share/nginx
    remote_src: yes