- name: Install Redis Package to get redis repos.
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: Install Redis
  yum:
    name: redis
    state: present
    enablerepo: "remi"
# enablerepo will usefull to yum command will  identify the automatically which ever in the latest package and will download the latest package..