- name: Install Maven
  yum:
    name:
      - maven
    state: installed

- name: Add Roboshop User
  ansible.builtin.user:
    name: roboshop
    comment: Roboshop Project User

- name: Download package
  include_role:
    name: common
    tasks_from: download-from-github
  vars:
    APP_DIR: /home/roboshop/{{COMPONENT}}
    EXTRACT_DIR: /tmp

# /home/roboshop-- actucally /tmp replaces with the /home/roboshop,,becz /tmp is the common place so no woories at all,,it will any how cleanup while reboot..
- name: copy content to actual directory
  copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}/
    remote_src: yes
  become_user: roboshop

- name: Build a Package with Maven
  shell: mvn clean package && mv target/{{COMPONENT}}-1.0.jar {{COMPONENT}}.jar
  args:
    chdir: /home/roboshop/{{COMPONENT}}
  become_user: roboshop

## in shell ansible module--- u can switch to another directory to use args ; chdir
- name: Copy SystemD file
  copy:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

## in this in root user cd /home/roboshop/catalogue all script is in root access,so thats why under the  become_user: roboshop will work...

- name: Start {{COMPONENT}} Service
  systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: yes
    daemon_reload: yes


