- name: Install Python
  yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: Add Roboshop User
  ansible.builtin.user:
    name: roboshop
    comment: Roboshop Project User

- name: Download package
  include_role:
    name: common
    tasks_from: download-from-github
  vars:
    APP_DIR: /home/roboshop/{{COMPONENT}}
    EXTRACT_DIR: /tmp

# /home/roboshop-- actucally /tmp replaces with the /home/roboshop,,becz /tmp is the common place so no woories at all,,it will any how cleanup while reboot..
- name: copy content to actual directory
  copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}/
    remote_src: yes
  become_user: roboshop

- name: Install specified python requirements
  pip:
    requirements: /home/roboshop/{{COMPONENT}}//requirements.txt
    executable: pip3

# exclusively say it is pip3 version so thats y mention 'excutable'

- name: Copy SystemD file
  copy:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

## in this in root user cd /home/roboshop/catalogue all script is in root access,so thats why under the  become_user: roboshop will work...

- name: Start {{COMPONENT}} Service
  systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: yes
    daemon_reload: yes


