- name: Add MySQL repository
  yum_repository:
    name: MySQL
    description: MySQL Repository
    baseurl: http://repo.mysql.com/yum/mysql-5.7-community/el/7/$basearch/
    enabled: yes
    gpgcheck: no
    file: mysql

- name: Remove MariaDB Libraries
  yum:
    name: mariadb.libs
    state: absent

- name: Install MySQL Server
  yum:
    name:
      - mysql-community-server
      - MySQL-python
    state: present

- name: Start MySQL Service
  systemd:
    name: mysqld
    state: started
    enabled: yes

- name: Check the MySQL Login
  community.mysql.mysql_query:
    login_user: root
    login_password: RoboShop@1
    query: show databases
  register: out
  ignore_errors: yes

## if u opn new server that RoboShop@1 is not first time password,so thats y if errors comes it will take care ignore_errors....just validation..even if a task is failure it can ignore.

- name: Reset MySQL Password
  block:
      - name: Grabing Default Password
        shell: grep "A temporary password" /var/log/mysqld.log | awk '{print $NF}'
        register: MYSQL_DEFAULT_PASSWORD

      - name: Copy Password Reset SQL Script
        copy:
          src: mysql-pass-reset.sql
          dest: /tmp/mysql-pass-reset.sql


      - name: Set MySQL Root Password
        shell: mysql --connect-expired-password -u root -p"{{MYSQL_DEFAULT_PASSWORD.stdout}}" < /tmp/mysql-pass-reset.sql
  when: out.failed


# .stdout is the going to have the password not the complete message...
# using block module u can keep some task inside that and u cn place the some condition