- name: Add MongoDB repository
  yum_repository:
    name: MongoDB
    description: MongoDB Repository
    baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.2/x86_64/
    enabled: yes
    gpgcheck: yes
    gpgkey:  https://www.mongodb.org/static/pgp/server-4.2.asc
    file: mongodb

## in cd /etc/yum/repos.d all repositories are in that path only,,,so in that MongoDB repository.repos so we can avoid that full name we will give  under file (mongodb)..it will take mongodb.repo,,bcz that spaces are  little confusion in linux..use rm -rf MongoDB/ repository.repos
## it dont take in name:MongoDB Repository so thats y just give MongoDB


- name: install MongoDB
  yum:
    name: mongodb-org
    state: present

- name: Update the MongnDB IP Address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  notify:
    - Restart MongoDB

## and then check in cat /etc/mongod.conf
## handlers will run at ending of the play

- name: Start MongoDB service
  systemd:
    name: mongod
    enabled: yes
    state: started

- name: Download package
  include_role:
    name: common
    tasks_from: download-from-github
  vars:
    APP_DIR: /tmp/mongodb-main
    EXTRACT_DIR: /tmp

## in root user cd /tmp and cd mongodb-main

- name: Load Schema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/{{item}}"
    idempotent: yes
  loop:
    - users.js
    - catalogue.js

## idempotent-Idempotence is the property of certain operations in mathematics and computer science whereby they can be applied multiple times without changing the result beyond the initial application.. Ansible is like idempotent bcz if anything is nt change it doesnt show in newer one,it shoes in intial one..
## idempotent-The module will not rerun the command if this file exists and idempotent is set to true.

