- name: Install NodeJS
  yum:
    name:
      - nodejs
      - make
      - gcc-c++
    state: latest

- name: Add Roboshop User
  ansible.builtin.user:
    name: roboshop
    comment: Roboshop Project User

- name: Download package
  include_role:
    name: common
    tasks_from: download-from-github
  vars:
    APP_DIR: /home/roboshop/catalogue
    EXTRACT_DIR: /home/roboshop

- name: copy content to actual directory
  copy:
    src: /home/roboshop/catalogue-main/
    dest: /home/roboshop/catalogue/
    remote_src: yes
  become_user: roboshop



## in this in root user cd /home/roboshop/catalogue all script is in root access,so thats why under the  become_user: roboshop will work...