- name: Demo on variable
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: print Variable
      debug:
        msg: URL = {{ URL }}


## Types of variables Pre-defined from user
## Play level variables
## Task leval variables
## Command line variables
## Inventory file variables
## Variable from a file