- name: Demo on variable
  hosts: all
  vars:
    URL: play.example.com #(play level)
  tasks:
    - name: print Variable
      debug:
        msg: URL = {{ URL }}
    - name: print variable from task #(task level)
      vars:
        URL: task.example.com
      debug:
        msg: URL = {{ URL }}

- name: Demo on variables from files
  hosts: all
  vars_files:
    - example-vars.yml
  tasks:
    - name: print variable from file
      debug:
        msg: URL = {{ URL }}

- name: Demo on variable from user input
  hosts: all
  vars_prompt:
    - name: URL
      prompt: ENTER URL
      private: false             #(to display the what ever u type a msg--(no or false or true)its a boolean's)
  tasks:
    - name: print variable
      debug:
      msg: URL = {{ URL }}




## Types of variables Pre-defined from user           ## highest priroity in the variables
## Play level variables                                           ##
## Task leval variables(local level)                          ##
## Command line variables                                    ##
## Inventory file variables                                      ##
## Variable from a file                                           ##
