- name: Demo on tags   #(task level)
  hosts: localhost
  tasks:
    - name: print fruits
      debug:
        msg: fruits
      tags:
        - fruits

    - name: print vegatables
      debug:
        msg: vegatables
      tags:
        - vegatables

- name: Demo on tags  #(play level)
  hosts: localhost
  tags:
    - AWS
  tasks:
    - name: print AWS
      debug:
        msg: AWS

- name: Demo on tags  #(play level)
  hosts: localhost
  tags:
    - Devops
  tasks:
    - name: print Devops
      debug:
        msg: Devops

## tag means whatever u want -t and that name will give,, it will show only that name only..In Task Level
## tag means whatever u want -t and that name will give,,  it will show only that name only remaining shows  in empty..In Play Level

