- name: Demo on tags
  hosts: localhost
  tasks:
    - name: print fruits
      debug:
        msg: fruits
      tags:
        - fruits

    - name: print vegatables
      debug:
        msg: vegatables
      tags:
        - vegatables