## in loops,it will usefull to iterate the same tasks  in multiple times..
## iterate-to say or do something again; repeat something

- name: Demo on loops
  hosts: localhost
  tasks:
    - name: print Fruits Name
      debug:
        msg: "{{item}}"
      loop:
        - banana
        - apple
        - mongo