- name: Demo on Conditions
  hosts: localhost
  vars:
    IS_RUN: false
  tasks:
     ## Boolean Condition
    - name: Run based on user input
      debug:
        msg: hello madhu
      when: IS_RUN
    ## String Condition
    - name: Print if this is Ubuntu OS
      debug:
        msg: Hello Ubuntu
      when: ansible

#   IS_RUN = is a bulean
# -e = overwritten meaning
# if bolean comes into picture we will use
# if string comes into picture we will use ==
# if numbers comes into picture we will use == or <