- name: ignore_errors Demo
  hosts: localhost
  tasks:
    - name: Fail this task
      fail:
        msg: Failing for Demo
     ignore_errors: yes

    - name: Print hello
      debug:
        msg: Hello