help:
	@echo

frontend:	## Install Frontend Component
	@sh Components/frontend.sh

mongodb:	## Install MongoDB Component
	@sh Components/mongodb.sh

catalogue:	## Install Catalogue Component
	@sh Components/catalogue.sh

redis:	## Install Redis Component
	@sh Components/redis.sh

mysql:	## Install Mysql Component
	@sh Components/mysql.sh

cart:	## Install Cart Component
	@sh Components/cart.sh

user:	## Install User Component
	@sh Components/user.sh

shipping:	## Install Shipping Component
	@sh Components/shipping.sh

rabbitmq:	## Install RabbitMQ Component
	@sh Components/rabbitmq.sh

payment:	## Install Payment Component
	@sh Components/payment.sh






